version: 0.0
os: linux

files:
  - source: /codepipeline.war
    destination: /opt/tomcat/apache-tomcat-9.0.69/webapps/
  - source: /TestXMLFile.xml
    destination: /opt/tomcat/apache-tomcat-9.0.69/webapps/
    
file_exists_behavior: OVERWRITE    
          
hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root 
